
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8080
        
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock 